### ISSUE TITLE
server.js is missing

### ISSUE THREAD

**Issue by purerosefallen** [ygoreplay/pro-server#36]
I was using the given Dockerfile to build the project. However, the entry file server.js seemed missing. How to get that file to make it working?

**Comment by async3619** [comment]
You need to build it first:

```
yarn build --release
docker build -t name-what-you-want
```

but as I mentioned in #2, you need to setup bunch of things before build this server.

**Comment by purerosefallen** [comment]
```
Step 6/13 : RUN yarn && yarn build
 ---> Running in 5e5925bcf820
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...

Error: Webpack compilation errors
    at /ygopro-server/tools/lib/runWebpack.ts:12:31
    at finalCallback (/ygopro-server/node_modules/webpack/lib/Compiler.js:257:39)
    at /ygopro-server/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/ygopro-server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/ygopro-server/node_modules/tapable/lib/Hook.js:154:20)
    at /ygopro-server/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/ygopro-server/node_modules/webpack/lib/Compiler.js:499:39)
    at /ygopro-server/node_modules/webpack/lib/Compiler.js:298:10
    at /ygopro-server/node_modules/webpack/lib/Compiler.js:485:14
    at eval (eval at create (/ygopro-server/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'pro-server' failed to build: The command '/bin/sh -c yarn && yarn build' returned a non-zero code: 1
```
same

**Comment by async3619** [comment]
got fixed, now you're should able to build it without sentry configuration.
